[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/tmux"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 17.0

[font.normal]
family = "HackNerdFontMono"
style = "Regular"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
