[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/tmux"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 1.0
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 17.0

[font.normal]
family = "HackNerdFontMono"
style = "Bold"

# Colors (Terminal.app)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#84c137'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#990000'
green   = '#00a600'
yellow  = '#999900'
blue    = '#0000b2'
magenta = '#b200b2'
cyan    = '#00a6b2'
white   = '#bfbfbf'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#e50000'
green   = '#00d900'
yellow  = '#e5e500'
blue    = '#0000ff'
magenta = '#e500e5'
cyan    = '#00e5e5'
white   = '#e5e5e5'

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
