
[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/tmux"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.8
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 17.0

[font.normal]
family = "HackNerdFontMono"
style = "Bold"

# Windows 95 Color Scheme
# To have the authentic experience in Chicago95 GTK Theme.

# Default colors
[colors.primary]
background = '#000000'
foreground = '#A85400'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#A80000'
green   = '#00A800'
yellow  = '#A85400'
blue    = '#0000A8'
magenta = '#A800A8'
cyan    = '#00A8A8'
white   = '#A8A8A8'

# Bright colors
[colors.bright]
black   = '#545454'
red     = '#FC5454'
green   = '#54FC54'
yellow  = '#FCFC54'
blue    = '#5454FC'
magenta = '#FC54FC'
cyan    = '#54FCFC'
white   = '#FFFFFF'

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
