import = []

live_config_reload = true

[shell]
program = "/usr/bin/tmux"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9
blur = false 

[scrolling]
history = 10000
multiplier = 3

[font]

# /home/william/.fonts/HackNerdFont-Regular.ttf: Hack Nerd Font:style=Regular
normal = { family ="Hack Nerd Font", style = "Regular" }

[colors.primary]
background = "#08080b"
foreground = "#787c99"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[bell]
animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
